import bcrypt from 'bcryptjs';
import * as db from './pool';
import type { UserRole } from '../types';

const DEMO_PASSWORD = 'Password123';
const FILLER_EVENT_COUNT = Number(process.env.SEED_EVENT_COUNT || 500);

const CITIES = [
  'Bengaluru',
  'Mumbai',
  'Delhi',
  'Pune',
  'Hyderabad',
  'Chennai',
  'Jaipur',
];

const TOPICS = [
  'React Workshop',
  'Node.js Bootcamp',
  'Startup Pitch Night',
  'UI/UX Meetup',
  'Data Science Summit',
  'Cloud Conclave',
  'Indie Music Evening',
  'Photography Walk',
  'AI Hackathon',
  'Product Management 101',
  'DevOps Day',
  'Open Source Saturday',
];

const pick = <T>(list: readonly T[]): T =>
  list[Math.floor(Math.random() * list.length)] as T;

const randomInt = (min: number, max: number): number =>
  Math.floor(Math.random() * (max - min + 1)) + min;

const daysFromNow = (days: number, hour = 18): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

interface SeedUser {
  id: number;
  email: string;
  role: UserRole;
}

async function hasExistingData(): Promise<boolean> {
  const { rows } = await db.query<{ count: number }>(
    'SELECT COUNT(*)::int AS count FROM users'
  );
  return (rows[0]?.count ?? 0) > 0;
}

async function seed(): Promise<void> {
  if (process.argv.includes('--if-empty') && (await hasExistingData())) {
    console.log('Database already has data - skipping seed.');
    await db.pool.end();
    return;
  }

  console.log('Seeding database...');

  await db.query(
    'TRUNCATE users, events, bookings, activity_log RESTART IDENTITY CASCADE'
  );

  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 10);

  const { rows: users } = await db.query<SeedUser>(
    `INSERT INTO users (name, email, password_hash, role)
     VALUES
       ('Anant Sharma',  'organizer@bookit.com',  $1, 'organizer'),
       ('Priya Menon',   'organizer2@bookit.com', $1, 'organizer'),
       ('Rahul Verma',   'user@bookit.com',       $1, 'user'),
       ('Sneha Iyer',    'user2@bookit.com',      $1, 'user'),
       ('Karan Gupta',   'user3@bookit.com',      $1, 'user')
     RETURNING id, email, role`,
    [passwordHash]
  );

  const organizers = users.filter((u) => u.role === 'organizer');
  const attendees = users.filter((u) => u.role === 'user');

  const showcaseEvents: [
    string,
    string,
    string,
    string,
    number,
    number
  ][] = [
    [
      'React India Meetup',
      'A hands-on evening about React 19, hooks and performance patterns. Snacks included.',
      'Tech Park Auditorium, Bengaluru',
      daysFromNow(3),
      50,
      49900,
    ],
    [
      'Node.js Deep Dive',
      'Build a production-ready REST API: transactions, indexes and error handling.',
      'WeWork Galaxy, Bengaluru',
      daysFromNow(6),
      30,
      79900,
    ],
    [
      'Startup Pitch Night',
      'Ten founders, five minutes each, one panel of investors.',
      'T-Hub, Hyderabad',
      daysFromNow(9),
      120,
      0,
    ],
    [
      'Sold Out Jazz Evening',
      'An intimate jazz session with a live quartet. Limited seating.',
      'Blue Door Cafe, Mumbai',
      daysFromNow(4),
      4,
      129900,
    ],
    [
      'Almost Full: UX Clinic',
      'Bring your product, get a live design critique from senior designers.',
      'Design Studio, Pune',
      daysFromNow(8),
      10,
      59900,
    ],
    [
      'Weekend Photography Walk',
      'Explore the old city at sunrise and learn street photography basics.',
      'City Palace Gate, Jaipur',
      daysFromNow(12),
      25,
      29900,
    ],
  ];

  const eventIds: number[] = [];

  for (const [
    title,
    description,
    venue,
    startsAt,
    capacity,
    priceCents,
  ] of showcaseEvents) {
    const organizerId = pick(organizers).id;

    const { rows } = await db.query<{ id: number }>(
      `INSERT INTO events (organizer_id, title, description, venue, starts_at, capacity, price_cents)
       VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id`,
      [organizerId, title, description, venue, startsAt, capacity, priceCents]
    );

    eventIds.push(rows[0]!.id);
  }

  const values: string[] = [];
  const params: unknown[] = [];

  for (let i = 0; i < FILLER_EVENT_COUNT; i += 1) {
    const organizerId = organizers[i % organizers.length]!.id;
    const base = params.length;

    params.push(
      organizerId,
      `${pick(TOPICS)} #${i + 1}`,
      'Sample event generated by the seed script so that search, filtering and pagination can be tested with a realistic number of rows.',
      `${pick(CITIES)} Convention Centre`,
      daysFromNow(randomInt(1, 180), randomInt(9, 20)),
      randomInt(20, 500),
      randomInt(0, 20) * 9900
    );

    values.push(
      `($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4}, $${base + 5}, $${base + 6}, $${base + 7})`
    );
  }

  if (values.length > 0) {
    await db.query(
      `INSERT INTO events (organizer_id, title, description, venue, starts_at, capacity, price_cents)
       VALUES ${values.join(', ')}`,
      params
    );
  }

  const jazzEventId = eventIds[3]!;
  const uxEventId = eventIds[4]!;
  const attendeeIds = attendees.map((u) => u.id);

  await bookSeats(jazzEventId, attendeeIds.slice(0, 3));
  await bookSeats(uxEventId, attendeeIds.slice(0, 2));
  await bookSeats(eventIds[0]!, attendeeIds.slice(0, 2));

  await db.query(
    'UPDATE events SET capacity = seats_booked WHERE id = $1',
    [jazzEventId]
  );

  for (const eventId of eventIds) {
    const viewCount = randomInt(15, 90);

    for (let i = 0; i < viewCount; i += 1) {
      await db.query(
        "INSERT INTO activity_log (event_id, user_id, type) VALUES ($1, $2, 'event_viewed')",
        [eventId, Math.random() > 0.4 ? pick(attendees).id : null]
      );
    }
  }

  console.log(
    `Seeded ${6 + FILLER_EVENT_COUNT} events, ${users.length} users.`
  );
  console.log(
    'Login with organizer@bookit.com / user@bookit.com  (password: Password123)'
  );

  await db.pool.end();
}

async function bookSeats(eventId: number, userIds: number[]): Promise<void> {
  for (const userId of userIds) {
    await db.withTransaction(async (client) => {
      await client.query(
        "INSERT INTO bookings (event_id, user_id, status) VALUES ($1, $2, 'confirmed')",
        [eventId, userId]
      );

      await client.query(
        'UPDATE events SET seats_booked = seats_booked + 1 WHERE id = $1',
        [eventId]
      );

      await client.query(
        "INSERT INTO activity_log (event_id, user_id, type) VALUES ($1, $2, 'booking_started')",
        [eventId, userId]
      );

      await client.query(
        "INSERT INTO activity_log (event_id, user_id, type) VALUES ($1, $2, 'booking_confirmed')",
        [eventId, userId]
      );
    });
  }
}

seed().catch((error: unknown) => {
  console.error('Seed failed:', error);
  process.exit(1);
});